### ISSUE TITLE
OpenLR encoding

### ISSUE THREAD

**Issue by Padarn** [tomtom-international/openlr-python#8]
Hi there,

I'm wondering if this package is intended for use in encoding geometries into OpenLR? I saw the recent work on https://github.com/tomtom-international/openlr-dereferencer-python and was wondering what the roadmap was for these two packages together.

**Comment by aksakalli** [comment]
Hi Padarn,

OpenLR format is a standard for transmitting and storing location references. `openlr` package only implements _xml_ and _binary_ physical formats which are described in the whitepaper.

If you need to store your own map and match the locations, you need `openlr-dereferencer` package. `openlr-dereferencer`  relies on `openlr` for location references. We separated these two packages in order to keep binary decoder client dependencies minimal with this lightweight, zero dependency Python package.

Please don't hesitate to ask further questions if something is not clear. Although both projects have scoop definition in the documentation, maybe we can improve the documentation to make it more clear.

**Comment by Padarn** [comment]
Hi @aksakalli thanks for your reply.

Sorry for asking basic questions but I'm not totally clear on terminology here

> OpenLR format is a standard for transmitting and storing location references. openlr package only implements xml and binary physical formats which are described in the whitepaper.

Can you explain what this mean? Implementing the binary and xml formats means that it implements encoding and decoding to that format? 

> If you need to store your own map and match the locations, you need openlr-dereferencer package

Sorry also confused by this. Can you give an example of how you intend this to be used. 

My (naive understanding) is that to use OpenLR you need 1) and encoder implementation and 2) a decoder implementation, both of which would need a map.

**Comment by aksakalli** [comment]
[The whitepaper](https://www.openlr-association.com/fileadmin/user_upload/openlr-whitepaper_v1.5.pdf) covers:

* Chapter D - Physical data format (Binary) 
* Chapter E - Physical data format (XML)
* Chapter F - Encoder
* Chapter G - Decoder

`openlr` package implements the physical formats like converting binary data to a python object (not map encoding/decoding in Chapter F & G).

For example, you have got a list of binary data for some location references and you want to classify them with some ML algorithm or convert this binary to GeoJSON to visualize in GIS system. You just need binary physical format to python object decoder in this package to tell `CwRbWyNG9RpsCQCb/jsbtAT/6/+jK1lE` is a `LineLocationReference` with points `(6.126819, 49.608517), (6.1283698, 49.603987), ... etc`. Regardless of map information, you can read the properties like "distance to next point" in your client code.  So `openlr` package's decoder/encoder infers binary decoding/encoding. 

`openlr` implements Chapter D, E
`openlr-dereferencer` implements F, G

**Comment by Padarn** [comment]
Ah, understood. I was confused as I thought it was the other way around (i.e `openlr` implements F and G). This makes a lot of sense now, thanks a lot for your help.
